#define selectText "SELECT * FROM table \nLIMIT 10;"
#define insertText "INSERT INTO table_name (first_name, last_name, email) \nVALUES ('John', 'Doe', 'john.doe@exampltable1.com');"
#define alterTableText "ALTER TABLE table_name ADD COLUMN phone VARCHAR(20);"
#define createTableText "CREATE TABLE table_name \n\t(employee_id INT PRIMARY KEY, first_name VARCHAR(50), last_name VARCHAR(50));"
#define deleteText "DELETE FROM table_name WHERE employee_id = 123;"
#define dropTableText "DROP TABLE table_name;"
#define joinText "SELECT table1.first_name, table1.last_name, table2.department_name \nFROM employees table1 \nJOIN departments table2 \nON table1.department_id = table2.department_id;"
#define orderByText "SELECT * FROM table_name ORDER BY hire_date DESC;"
#define updateText "UPDATE table_name \nSET email = 'jane.doe@example.com' \nWHERE first_name = 'Jane' \nAND last_name = 'Doe';"
#define whereText "SELECT * FROM table_name \nWHERE department = 'Sales';"
